export PYTHONPATH=src:abstractive-models:extractive-models

python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.1/lr=8e-6/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.1,lr=8e-6.jsonl
python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.2/lr=8e-6/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.2,lr=8e-6.jsonl
python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.3/lr=8e-6/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.3,lr=8e-6.jsonl
python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.4/lr=8e-6/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.4,lr=8e-6.jsonl

python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.1/lr=4e-5/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.1,lr=4e-5.jsonl
python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.2/lr=4e-5/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.2,lr=4e-5.jsonl
python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.3/lr=4e-5/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.3,lr=4e-5.jsonl
python src/neuraldb/commands/predict_pipeline.py --model_name_or_path null --train_path null --val_path null --cls_model /scratch/jth/neuraldb/nuo_cls --nuo_model /checkpoint/jth/job_staging/neuraldb_expts/experiment=operator_sweep/dataset=operator,model=t5-base,version=v1.1.4/lr=4e-5/filters=null,train_percentage=1.0/seed-1/ --in_file v0.5/dev_queries_last_50.json --out_file pipeline_predictions/db=50,data=v0.5,model=v1.1.4,lr=4e-5.jsonl