python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-3/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-3/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-3/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-3/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-3/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-5/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-5/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-5/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-5/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-5/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-5/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-5/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-5/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-5/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-5/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-4/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-4/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-4/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-4/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=1e-4/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=entire_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever all   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=iterate_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf --iterate  --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=100,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=1000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_1000.json --val_path=v0.5/dev_queries_last_1000.json --test_path=v0.5/dev_queries_last_1000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=500,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_500.json --val_path=v0.5/dev_queries_last_500.json --test_path=v0.5/dev_queries_last_500.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=2000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_2000.json --val_path=v0.5/dev_queries_last_2000.json --test_path=v0.5/dev_queries_last_2000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=7000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_7000.json --val_path=v0.5/dev_queries_last_7000.json --test_path=v0.5/dev_queries_last_7000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=10000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_10000.json --val_path=v0.5/dev_queries_last_10000.json --test_path=v0.5/dev_queries_last_10000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=5000,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_5000.json --val_path=v0.5/dev_queries_last_5000.json --test_path=v0.5/dev_queries_last_5000.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=100,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=100,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=100,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=100,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=100,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0008/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=100,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=100,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=100,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=100,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_concat/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=0.0005/context=100,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 4 --eval_batch_size 4 --n_gpu 4 --train_path=v0.5/train_queries_last_100.json --val_path=v0.5/dev_queries_last_100.json --test_path=v0.5/dev_queries_last_100.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database_large/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database_large/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database_large/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database_large/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-5 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=search_database_large/dataset=ndb,model=t5-base,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf   --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_large/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-1 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_large/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-3 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_large/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-4 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
python -m neuraldb.commands.t5train2 --output_dir /checkpoint/jth/neuraldb/final=true/experiment=oracle_large/dataset=ndb,model=t5-base,oracle=true,version=v0.5/lr=5e-4/context=50,filters=null,max_queries=null/seed-2 --model_name_or_path t5-base --do_predict --train_batch_size 16 --eval_batch_size 16 --n_gpu 4 --train_path=v0.5/train_queries_last_50.json --val_path=v0.5/dev_queries_last_50.json --test_path=v0.5/dev_queries_last_50.json --retriever tfidf  --oracle --dataset_version=v0.5
